image: golang:1.20.1

stages:
  - test

cicd:
  stage: test
  variables:
    UNITTEST_GCP_PROJECT_ID: cicd-389504
    GOOGLE_APPLICATION_CREDENTIALS: .secure_files/gcp-cicd-pubsub-sa-creds.json
    GOOGLE_EXTERNAL_ACCOUNT_ALLOW_EXECUTABLES: "1"
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - go fmt $(go list ./...)
    - go vet $(go list ./...)
    - go test ./...
