image: golang:1.20.1

stages:
  - test

cicd:
  stage: test
  variables:
    UNITTEST_GCP_PROJECT_ID: cicd
    GOOGLE_APPLICATION_CREDENTIALS: ./cicd/gcp_cred_cfg.json
    GOOGLE_EXTERNAL_ACCOUNT_ALLOW_EXECUTABLES: "1"
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://iam.googleapis.com/projects/762069519666/locations/global/workloadIdentityPools/cicd-workflow/providers/gitlab
  script:
    - go fmt $(go list ./...)
    - go vet $(go list ./...)
    - go test ./...
