name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  golint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: golint
        uses: Jerome1337/golint-action@v1.0.3
        with:
          golint-path: "./..."

  golangci-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.57.2
          args: --timeout 3m0s

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Test
        env:
          UNITTEST_GCP_PROJECT_ID: cicd-389504
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-creds.json
          GOOGLE_APPLICATION_CREDENTIALS_VAL: ${{ secrets.GOOGLEAPPLICATIONCREDENTIALSVAL }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS_VAL" > /tmp/gcp-creds.json
          go test --count 1 -v -timeout 600s -short ./...
